[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn fibertruck.wsgi:application"
healthcheckPath = "/api/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
