[build]
builder = "nixpacks"
buildCommand = "bash build.sh"

[deploy]
startCommand = "bash railway_entrypoint.sh"
healthcheckPath = "/health/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
