# Generated by Django 6.0.6 on 2026-07-01 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiberBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Numero de caja que introduce el tecnico. Ej: CTO-001', max_length=20, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('box_type', models.CharField(choices=[('CTO', 'Caja de Terminacion Optica (CTO)'), ('CTO-MINI', 'CTO Mini'), ('FAT', 'Fiber Access Terminal'), ('FDT', 'Fiber Distribution Terminal')], default='CTO', max_length=20, verbose_name='Tipo')),
                ('splitter_port', models.PositiveIntegerField(default=0, verbose_name='Puerto del splitter')),
                ('max_capacity', models.PositiveIntegerField(default=16, verbose_name='Capacidad maxima')),
                ('latitude', models.FloatField(verbose_name='Latitud')),
                ('longitude', models.FloatField(verbose_name='Longitud')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Direccion')),
                ('status', models.CharField(choices=[('active', 'Activa - OK'), ('warning', 'Advertencia'), ('fault', 'Con averia'), ('maintenance', 'En mantenimiento'), ('inactive', 'Inactiva')], default='active', max_length=20, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas tecnicas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Caja de Fibra',
                'verbose_name_plural': 'Cajas de Fibra',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OLT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Ej: OLT-CIEZA-01', max_length=20, unique=True, verbose_name='Codigo')),
                ('address', models.CharField(max_length=200, verbose_name='Direccion')),
                ('latitude', models.FloatField(verbose_name='Latitud')),
                ('longitude', models.FloatField(verbose_name='Longitud')),
                ('max_ports', models.PositiveIntegerField(default=16, verbose_name='Puertos PON maximos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OLT',
                'verbose_name_plural': 'OLTs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Ej: Z-SJOA', max_length=20, unique=True, verbose_name='Codigo')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('latitude', models.FloatField(verbose_name='Latitud centro')),
                ('longitude', models.FloatField(verbose_name='Longitud centro')),
                ('population_estimate', models.PositiveIntegerField(default=0, verbose_name='Poblacion estimada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(help_text='Ej: CLI-0001', max_length=20, unique=True, verbose_name='Codigo cliente')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('address', models.CharField(max_length=300, verbose_name='Direccion de instalacion')),
                ('latitude', models.FloatField(verbose_name='Latitud')),
                ('longitude', models.FloatField(verbose_name='Longitud')),
                ('box_port', models.PositiveIntegerField(default=0, verbose_name='Puerto de la caja')),
                ('olt_port', models.PositiveIntegerField(default=0, verbose_name='Puerto PON OLT')),
                ('status', models.CharField(choices=[('active', 'Activo - Servicio OK'), ('affected', 'Afectado - Sin servicio'), ('degraded', 'Degradado - Velocidad baja'), ('installing', 'En instalacion'), ('disconnected', 'Desconectado')], default='active', max_length=20, verbose_name='Estado')),
                ('optical_power_rx', models.FloatField(blank=True, null=True, verbose_name='Potencia RX (dBm)')),
                ('optical_power_tx', models.FloatField(blank=True, null=True, verbose_name='Potencia TX (dBm)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Fecha instalacion')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='network.fiberbox', verbose_name='Caja asignada')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['client_code'],
            },
        ),
        migrations.CreateModel(
            name='Splitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ej: SPL-001', max_length=20, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('ratio', models.CharField(choices=[('1x2', '1x2'), ('1x4', '1x4'), ('1x8', '1x8'), ('1x16', '1x16'), ('1x32', '1x32'), ('1x64', '1x64')], default='1x32', max_length=10, verbose_name='Ratio')),
                ('input_port_olt', models.PositiveIntegerField(default=0, verbose_name='Puerto PON OLT')),
                ('latitude', models.FloatField(verbose_name='Latitud')),
                ('longitude', models.FloatField(verbose_name='Longitud')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Direccion/Ubicacion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splitters', to='network.olt', verbose_name='OLT padre')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splitters', to='network.zone', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Splitter',
                'verbose_name_plural': 'Splitters',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FiberIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ej: INC-20250701-001', max_length=20, unique=True, verbose_name='Codigo')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('incident_type', models.CharField(choices=[('fiber_break', 'Rotura de fibra'), ('splitter_fault', 'Fallo en splitter'), ('connector_fault', 'Fallo en conector'), ('olt_fault', 'Fallo en OLT'), ('power_issue', 'Problema de potencia optica'), ('unknown', 'Desconocido')], default='unknown', max_length=20, verbose_name='Tipo')),
                ('severity', models.CharField(choices=[('critical', 'Critica - Corte total zona'), ('high', 'Alta - Multiples afectados'), ('medium', 'Media - Individual'), ('low', 'Baja - Degradacion')], default='medium', max_length=20, verbose_name='Severidad')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('diagnosing', 'En diagnostico'), ('assigned', 'Asignada a tecnico'), ('in_progress', 'En reparacion'), ('resolved', 'Resuelta'), ('closed', 'Cerrada')], default='open', max_length=20, verbose_name='Estado')),
                ('diagnosis_result', models.TextField(blank=True, verbose_name='Resultado del diagnostico')),
                ('diagnosis_confidence', models.FloatField(default=0.0, verbose_name='Confianza del diagnostico (%)')),
                ('root_cause_node', models.CharField(blank=True, max_length=50, verbose_name='Nodo causa raiz')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('reported_by', models.CharField(blank=True, max_length=100, verbose_name='Reportado por')),
                ('assigned_to', models.CharField(blank=True, max_length=100, verbose_name='Tecnico asignado')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha resolucion')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de resolucion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_clients', models.ManyToManyField(blank=True, related_name='incidents', to='network.client', verbose_name='Clientes afectados')),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='network.fiberbox', verbose_name='Caja afectada')),
                ('olt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='network.olt', verbose_name='OLT afectado')),
                ('splitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='network.splitter', verbose_name='Splitter afectado')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='fiberbox',
            name='splitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='network.splitter', verbose_name='Splitter padre'),
        ),
        migrations.AddField(
            model_name='fiberbox',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='network.zone', verbose_name='Zona'),
        ),
    ]
