# Generated by Django 4.2.30 on 2026-07-02 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_ftth_engineering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Activo - Servicio OK'), ('affected', 'Afectado - Sin servicio'), ('degraded', 'Degradado'), ('installing', 'En instalacion'), ('disconnected', 'Desconectado')], default='active', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='fiberincident',
            name='affected_clients',
            field=models.ManyToManyField(blank=True, related_name='incidents', to='network.client'),
        ),
        migrations.AlterField(
            model_name='fiberincident',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='network.fiberbox'),
        ),
        migrations.AlterField(
            model_name='fiberincident',
            name='olt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='network.olt'),
        ),
        migrations.AlterField(
            model_name='fiberincident',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critica'), ('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], default='medium', max_length=20, verbose_name='Severidad'),
        ),
        migrations.AlterField(
            model_name='fiberincident',
            name='splitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='network.splitter'),
        ),
        migrations.AlterField(
            model_name='fiberincident',
            name='status',
            field=models.CharField(choices=[('open', 'Abierta'), ('diagnosing', 'En diagnostico'), ('assigned', 'Asignada'), ('in_progress', 'En reparacion'), ('resolved', 'Resuelta'), ('closed', 'Cerrada')], default='open', max_length=20, verbose_name='Estado'),
        ),
    ]
