# Generated by Django 4.2.30 on 2026-07-02 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0003_alter_client_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Formato: FT-YYYY-NNNNNN', max_length=20, unique=True, verbose_name='Código de ticket')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('ticket_type', models.CharField(choices=[('home_fault', 'Avería en domicilio'), ('network_fault', 'Avería en red'), ('degradation', 'Degradación de servicio'), ('installation', 'Instalación nueva'), ('maintenance', 'Mantenimiento preventivo')], default='home_fault', max_length=20, verbose_name='Tipo de incidencia')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('assigned', 'Asignado'), ('in_transit', 'En desplazamiento'), ('in_progress', 'En trabajo'), ('paused', 'Pausado'), ('needs_material', 'Pendiente de material'), ('needs_client', 'Pendiente de cliente'), ('resolved', 'Resuelto - Pendiente verificación'), ('escalated', 'Escalado'), ('closed', 'Cerrado'), ('cancelled', 'Cancelado'), ('reopened', 'Reabierto')], default='open', max_length=20, verbose_name='Estado')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Dirección de la incidencia')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('sla_hours', models.PositiveSmallIntegerField(default=24, verbose_name='SLA (horas)')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite de resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('root_cause', models.CharField(blank=True, max_length=200, verbose_name='Causa raíz')),
                ('solution_applied', models.TextField(blank=True, verbose_name='Solución aplicada')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de resolución')),
                ('optical_power_final', models.FloatField(blank=True, null=True, verbose_name='Potencia óptica final (dBm)')),
                ('tracking_token', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Token de seguimiento')),
                ('estimated_resolution', models.DateTimeField(blank=True, null=True, verbose_name='Resolución estimada')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='network.fiberbox', verbose_name='Caja afectada')),
                ('affected_splitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='network.splitter', verbose_name='Splitter afectado')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Técnico asignado')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='network.client', verbose_name='Cliente afectado')),
                ('coordinator', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'supervisor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador responsable')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=20, verbose_name='Estado anterior')),
                ('new_status', models.CharField(max_length=20, verbose_name='Estado nuevo')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Histórico de estado',
                'verbose_name_plural': 'Histórico de estados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Contenido')),
                ('visibility', models.CharField(choices=[('internal', 'Interna'), ('client', 'Visible para cliente')], default='internal', max_length=20, verbose_name='Visibilidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_comments', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('photo_before', 'Foto estado previo'), ('photo_during', 'Foto durante trabajo'), ('photo_after', 'Foto resultado'), ('meter_reading', 'Lectura de medidor'), ('document', 'Documento')], default='photo_before', max_length=20, verbose_name='Tipo de adjunto')),
                ('file', models.ImageField(upload_to='ticket_attachments/%Y/%m/%d/', verbose_name='Archivo')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket', verbose_name='Ticket')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(blank=True, default=list, help_text='Lista de skills: home, network, splicing, installation', verbose_name='Habilidades')),
                ('max_workload', models.PositiveSmallIntegerField(default=5, help_text='Número máximo de tickets que puede tener asignados simultáneamente', verbose_name='Carga máxima de tickets activos')),
                ('current_latitude', models.FloatField(blank=True, null=True, verbose_name='Latitud actual')),
                ('current_longitude', models.FloatField(blank=True, null=True, verbose_name='Longitud actual')),
                ('location_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Última actualización de ubicación')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de técnico',
                'verbose_name_plural': 'Perfiles de técnicos',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'priority'], name='tickets_tic_status_b256f6_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to', 'status'], name='tickets_tic_assigne_e36302_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_5dd600_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['code'], name='tickets_tic_code_2520cc_idx'),
        ),
    ]
