# Generated by Django 4.2.30 on 2026-07-05 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_client_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=20, verbose_name='Severidad')),
                ('confidence', models.PositiveSmallIntegerField(default=0, verbose_name='Confianza %')),
                ('power_analysis', models.JSONField(default=dict, verbose_name='Análisis de potencia')),
                ('affected_clients', models.JSONField(default=list, verbose_name='Clientes afectados')),
                ('possible_solutions', models.JSONField(default=list, verbose_name='Posibles soluciones')),
                ('recommended_action', models.TextField(blank=True, verbose_name='Acción recomendada')),
                ('affected_route', models.JSONField(default=list, verbose_name='Ruta afectada')),
                ('solution_applied', models.TextField(blank=True, verbose_name='Solución aplicada')),
                ('resolved', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_logs', to='network.fiberbox', verbose_name='Caja afectada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_logs', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('splitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_logs', to='network.splitter', verbose_name='Splitter afectado')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_logs', to='tickets.ticket', verbose_name='Ticket operativo')),
            ],
            options={
                'verbose_name': 'Registro de diagnóstico',
                'verbose_name_plural': 'Registros de diagnóstico',
                'ordering': ['-created_at'],
            },
        ),
    ]
